---
- key: kojo
  name: Kojo
  summary: Command line utility for generating config files from templates and definition
    files
  lang: Ruby
  tags:
  - ruby
  - templating
  - configuration-tools
  - cli
