- name: Jobly
  image: featured/jobly.svg
  summary: Job Server
  link: https://jobly.dannyb.co/

- name: Madness
  image: featured/madness.svg
  summary: Instant Markdown Server
  link: https://madness.dannyb.co/

- name: Victor
  image: featured/victor.svg
  summary: Ruby to SVG
  link: https://github.com/dannyben/victor

- name: Opcode
  image: featured/opcode.svg
  summary: Local Command Shortcuts
  link: https://github.com/dannyben/opcode

- name: Alf
  image: featured/alf.svg
  summary: Bash Alias Manager
  link: https://github.com/dannyben/alf

- name: Bashly
  image: featured/bashly.svg
  summary: Bash command line framework and CLI generator
  link: https://github.com/dannyben/bashly
