- name: Bashly
  image: bashly.png
  summary: Bash command line framework and CLI generator
  link: https://bashly.dannyb.co/

- name: Jobly
  image: jobly.png
  summary: Job Server
  link: https://jobly.dannyb.co/

- name: Opcode
  image: opcode.png
  summary: Local Command Shortcuts
  link: https://github.com/dannyben/opcode

- name: Madness
  image: madness.png
  summary: Instant Markdown Server
  link: https://madness.dannyb.co/

- name: Victor
  image: victor.png
  summary: Ruby to SVG
  link: https://github.com/dannyben/victor

- name: Alf
  image: alf.png
  summary: Bash Alias Manager
  link: https://github.com/dannyben/alf

